image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://docker:2375"
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - get-integration-tests
  - integration
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package"
  artifacts:
    paths:
      - target/*.jar

get-integration depot:
  image: carver/docker-git
  stage: get-integration-tests
  script:
    - git clone https://compareIT:myyvlqtfrryo7wkopcv2w42lgx2wjfeylxq6ethdismwwmt77j6a@dev.azure.com/compareIT/COMPARE-IT/_git/CITTESTI
    - cd CITESTI

maven-integration-tests:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package"
  artifacts:
    paths:
      - target/*.jar


docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/compare-it/compare-it-back .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/compare-it/compare-it-back

docker-deploy:
  image: rastasheep/ubuntu-sshd
  stage: deploy
  script:
  - pwd
  - ls
  - chmod 600 ../compare-it-back.tmp/SSH_PEM_KEY
  - ssh -i $SSH_PEM_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@35.180.27.13 './start_project'
  only:
  - master


