image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://docker:2375"
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - staging
  - test
  - production

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/compare-it/compare-it-back .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/compare-it/compare-it-back
  only:
    - develop

job_deploy_staging:
  image: rastasheep/ubuntu-sshd
  stage: staging
  script:
  - echo "deploy the app into test (valserver)"
  - pwd
  - ls
  - chmod 600 ../compare-it-back.tmp/SSH_PEM_KEY
  - ssh -i $SSH_PEM_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@compit.ddns.net './start_project'
  environment: 
    name: staging
  only:
  - develop

job_deploy_prod: 
  image: rastasheep/ubuntu-sshd
  stage: production
  script:
    - echo "deploy the app into prod"
    - pwd
    - ls
    - chmod 600 ../compare-it-back.tmp/SSH_PEM_KEY
    - ssh -i $SSH_PEM_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null msn@compit2.northeurope.cloudapp.azure.com './start_project'
  environment:
    name: production
  only:
    - fix/xdevapi
    - master




